### PR TITLE
SCRUM-271

### PR DESCRIPTION
**Pull request by cmpich**

### CODE REVIEW

**Comment by oblodgett** [comment]
@cmpich does this need to go into release-4.2.0?

**Comment by cmpich** [comment]
It would be nice but it needs to get checked first on BUILD.

**Comment by oblodgett** [comment]
build is not running anymore

**Comment by cmpich** [comment]
Where can I test it then?

**Comment by oblodgett** [comment]
is this going out for 4.2? if so it needs to go on stage aka release-4.2.0 branch

**Comment by cmpich** [comment]
I don't know. It was marked as 4.2 before the DOR was renamed from 4.1.1 to 4.2.
Should ask Chris.
However, I would like to test it on a non-stage environment.
Why is BUILD not running?

**Comment by oblodgett** [comment]
This is the same process that we have been doing for 4 years now. We make a new release starting it on build once build gets to a point we take release branches and move the release form build to stage. This happened last week, so any new code (bug fixes, whatever) needs to go into the release branches in order to go out with the release (4.2.0) and will be seen on stage. Typically build would be pointed at 5.0.0 at this point.

**Review by oblodgett — APPROVED** [review]

**Review by oblodgett — CHANGES_REQUESTED** [review]
Release Branch vs master?

**Review by oblodgett — APPROVED** [review]

**Pull request merged**
