### PR TITLE
fix AGR-2627 stringencyFilter issue

### PR DESCRIPTION
**Pull request by FB-ping**
fix AGR-2627 orthology stringencyFilter issue

### CODE REVIEW

**Review by oblodgett — COMMENTED** [review]
This may effect the data in the cache? Is this intended?

**Comment by FB-ping** [comment]
> This may effect the data in the cache? Is this intended?

yes, will affect cache and reversed to original code.

**Comment by FB-ping** [comment]
> This may effect the data in the cache? Is this intended?

@oblodgett more, I checked the history of those files, and reversed code and tested local cacher server.  look fine as expect.

**Review by cmpich — COMMENTED** [review]
Looks good.

**Pull request merged**
