### PR TITLE
SCRUM-4150 validate various entities of disease annotation for being …

### PR DESCRIPTION
**Pull request by cmpich**
…obsolete

### CODE REVIEW

**Review by markquintontulloch — COMMENTED** [review]
Do we need to add 'with' genes to the list of stuff to be checked?

**Review by oblodgett — APPROVED** [review]

**Comment by markquintontulloch** [comment]
Does anything extra need to be done for the inferred annotations?

**Comment by oblodgett** [comment]
Sorry approved this too fast, isn't there an asserted Gene also?

**Review by markquintontulloch — CHANGES_REQUESTED** [review]
Pretty sure 'with' needs to be added to the list of things to validate, otherwise looks good.  Don't know if any extra logic is required for the inferred annotations.

**Comment by cmpich** [comment]
The inferred/asserted genes and alleles are all included already in the logic.
The inferred annotations are using entities that have been checked before they get created.
I added the With-Genes.

**Comment by cmpich** [comment]
Do not merge this until 7.2.0 is deployed and 7.3.0 is prepared on stage repo.

**Review by markquintontulloch — APPROVED** [review]

**Comment by markquintontulloch** [comment]
Just thought, shouldn't we also be checking internal status on all of these things too?

**Pull request merged**
