### PR TITLE
AGR-2892

### PR DESCRIPTION
**Pull request by adamgibs**

### CODE REVIEW

**Review by oblodgett — COMMENTED** [review]
Are these going to get changed via the Human File? If so we need to wait on the new file before making code changes?

**Comment by adamgibs** [comment]
Oh, that's a good point. I'm not sure. I'll hold off on these changes then.

**Comment by gildossantos** [comment]
I'm still seeing the odd variant types that this PR was intended to suppress. Has the new human file had enough time to percolate through to the search UI on BUILD? If so, then should we reopen this PR now?

**Comment by adamgibs** [comment]
@gildossantos I'm not sure about this. @oblodgett Is the new human file on build yet?

**Comment by oblodgett** [comment]
No we are trying to trace down a major slowdown in the code that is causing the indexer to go from 1.25 hours to 4.5 hours. Once we can sort that out... will implement the new human file.

**Comment by gildossantos** [comment]
The human variants are back on BUILD, which I take to mean that the new human VCF file has been processed and all changes have percolated to the front end. If that's true, then the new file didn't fix the issue with the odd variant types, so perhaps we should reopen this PR now?

**Comment by oblodgett** [comment]
Nope... its just that the human indexer happened to run and import an new index but the files are being uploaded right now.

**Pull request closed without merging**
