### PR TITLE
Import and whitespace cleanup

### PR DESCRIPTION
**Pull request by oblodgett**

### CODE REVIEW

**Comment by markquintontulloch** [comment]
Are all the spacing changes intended?

**Comment by oblodgett** [comment]
Ya you are right i need to split this out. The organize in eclipse did this, i thought the tab space issue has been fixed in prior commits.

**Review by cmpich — COMMENTED** [review]
It's hard to see what really has changed. Most modifications are space changes. Could you list the files that contain the relevant changes?

**Comment by oblodgett** [comment]
@cmpich and @markquintontulloch I am going to split out the change from the formatting... once I take care of this other issue.

**Comment by oblodgett** [comment]
One way to make this easier at least for this PR:

Screen Shot 2022-09-19 at 4 09 18 PM

**Review by markquintontulloch — APPROVED** [review]

**Pull request merged**
