### PR TITLE
AGR-2842 added species to TranscriptLevelConsequence

### PR DESCRIPTION
**Pull request by adamgibs**
After we changed line 114 in the AlleleVariantSequenceConverter to use getNameKey(), it still didn't appear to append the species abbreviation to the gene symbol on build. So I tried running the variant indexer with the debugger and noticed that species was always null within the getNameKey() method. 
	
In TranscriptLevelConsequence, setSpecies was never called on associatedGene and that the infos doesn't  contain species. So I passed down species from AlleleVariantSequenceConverter to TranscriptLevelConsequence

### CODE REVIEW

**Comment by oblodgett** [comment]
I would do this differently so that there wasn't such a breaking change. Right after line 116 in the AVS Converter I would just add the following:
`c.getAssociatedGene().setSpecies(species)` this way the species object doesn't have to be passed around its already a class level variable.

**Comment by adamgibs** [comment]
@oblodgett Update has been pushed out

**Comment by oblodgett** [comment]
I think you might want it to happen outside the larger if statement: `if(!transcriptsProcessed.contains(c.getTranscriptID())) {` ??

**Comment by adamgibs** [comment]
@oblodgett Okay, sure. I will do that. From what I can tell, it just needs to happen before the `genes.add(c.getAssociatedGene().getNameKey());` line so that species isn't null within the getNameKey() method:         
```
if (species != null) {
            nameKey += " (" + species.getType().getAbbreviation() + ")";
        }
```
So should I add the change prior to the `if(!transcriptsProcessed.contains(c.getTranscriptID()))`, probably on line 101?

**Comment by oblodgett** [comment]
Ya... before (line 102) or after (line 119) the if statement I don't think really matters. It just needs to be outside of the if statement, so that it it happens for all TLC's that are created.

**Review by oblodgett — APPROVED** [review]

**Pull request merged**
