### PR TITLE
SCRUM-2704 add paralogy chacher infrastructure plus new endpoint for paralogy

### PR DESCRIPTION
**Pull request by cmpich**
…paralogy

### CODE REVIEW

**Review by oblodgett — CHANGES_REQUESTED** [review]
Shouldn't the OrthologView be change for ParalogView?

**Review by oblodgett — COMMENTED** [review]
And the `@JsonView(View.Orthology.class)` be changed for a `@JsonView(View.Paralogy.class)`?

**Comment by cmpich** [comment]
I did not introduce a new view as the existing one, View.Orthology, is just working fine without any changes. If we ever have a need I would split this view up into the two. Maybe, the view should be called View.Homology.class?

**Comment by cmpich** [comment]
Removed ParalogyView class and renamed View.Orthology to View.Homology

**Comment by oblodgett** [comment]
See my slack comments.

**Review by oblodgett — APPROVED** [review]

**Pull request merged**
