### PR TITLE
Updated default tag for linux env.

### PR DESCRIPTION
**Pull request by christabone**

### CODE REVIEW

**Review by oblodgett — APPROVED** [review]
Sorry didnt catch all these

**Comment by mluypaert** [comment]
@christabone @oblodgett  Why changing the defaults rather than using env variables when running the Docker build's? We originally set these `latest` as default tag value to prevent accidental overwrites of GoCD-generated images like `stage`, or production images like specific release numbers.

**Comment by christabone** [comment]
I'll defer to Olin on this one, this is his decision that I was implementing in the code.

**Comment by christabone** [comment]
The latest images are also gone, so setting them as default doesn't really make much sense anymore from that perspective.

**Pull request merged**
